# Generated by Django 5.0 on 2023-12-31 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('unit_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoInfo.invoice')),
            ],
        ),
    ]
