# Generated by Django 5.0 on 2024-01-01 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
