# Generated by Django 5.0 on 2024-01-01 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoInfo', '0002_invoicedetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
