# Generated by Django 5.0 on 2024-01-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoInfo', '0003_alter_invoicedetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='invoInfo.invoice'),
        ),
    ]
